use_frameworks!

platform :ios, '10.0'

target 'BackgroundRemoval_Example' do
  pod 'BackgroundRemoval', :path => '../'

  target 'BackgroundRemoval_Tests' do
    inherit! :search_paths

    
  end
end
